# Generated by Django 3.2 on 2021-04-11 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True, verbose_name='Latitude')),
                ('long', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True, verbose_name='Longitude')),
                ('lookup_json', models.JSONField(blank=True, null=True, verbose_name='Address Lookup Result (edits will not be saved)')),
            ],
            options={
                'verbose_name_plural': ' Locations',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '12345678'", regex='^\\d{8}$')])),
            ],
            options={
                'verbose_name_plural': '  Workers',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique_for_date='start_date')),
                ('note', models.TextField(blank=True, verbose_name='Notes')),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_scheduler.location')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_scheduler.worker')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
