# Generated by Django 3.2 on 2021-04-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Meeting Date'),
        ),
    ]
